nvm = ["no", "nvm", "nevermind", "cancel", "oops"]

default_commands = ['hi','help','attend','weather','dota','dotes','dop','doto','guess','aoe','randomciv','deletefrom','greetings','conversation','commands','tables']

random_responses = ["Read any good books lately?","Let's play some dota","Wha?","Not sure about that","You are like friend if mine who look for fight in early game and create space for the team, but sadly my friend play the carry role.","Say peacock and no one bats an eye... say poopcock and society goes wild","and in the end, after long time the match ended, u realized that she is a girl, a beautiful girl like u have been dreaming of all this time. what would u do? what do u say?"]
    
heroes = ["Abaddon","Alchemist","Axe","Beastmaster","Brewmaster","Bristleback","Centaur Warrunner","Chaos Knight","Clockwerk","Dawnbreaker","Doom","Dragon Knight","Earth Spirit","Earthshaker","Elder Titan","Huskar","Kunkka","Legion Commander","Lifestealer","Lycan","Magnus","Marci","Mars","Night Stalker","Omniknight","Phoenix","Pudge","Sand King","Slardar","Snapfire","Spirit Breaker","Sven","Tidehunter","Timbersaw","Tiny","Treant Protector","Tusk","Underlord","Undying","Wisp","Wraith King","Anti-Mage","Arc Warden","Bloodseeker","Bounty Hunter","Broodmother","Clinkz","Drow Ranger","Ember Spirit","Faceless Void","Gyrocopter","Hoodwink","Juggernaut","Lone Druid","Luna","Medusa","Meepo","Mirana","Monkey King","Morphling","Naga Siren","Nyx Assassin","Pangolier","Phantom Assassin","Phantom Lancer","Razor","Riki","Shadow Fiend","Slark","Sniper","Spectre","Templar Assassin","Terrorblade","Troll Warlord","Ursa","Vengeful Spirit","Venomancer","Viper","Weaver","Ancient Apparition","Bane","Batrider","Chen","Crystal Maiden","Dark Seer","Dark Willow","Dazzle","Death Prophet","Disruptor","Enchantress","Enigma","Grimstroke","Invoker","Jakiro","Keeper of the Light","Leshrac","Lich","Lina","Lion","Nature's Prophet","Necrophos","Ogre Magi","Oracle","Outworld Devourer","Puck","Pugna","Queen of Pain","Rubick","Shadow Demon","Shadow Shaman","Silencer","Skywrath Mage","Storm Spirit","Techies","Tinker","Visage","Void Spirit","Warlock","Windranger","Winter Wyvern","Witch Doctor","Zeus"]
stre = ["Abaddon","Alchemist","Axe","Beastmaster","Brewmaster","Bristleback","Centaur Warrunner","Chaos Knight","Clockwerk","Dawnbreaker","Doom","Dragon Knight","Earth Spirit","Earthshaker","Elder Titan","Huskar","Kunkka","Legion Commander","Lifestealer","Lycan","Magnus","Marci","Mars","Night Stalker","Omniknight","Phoenix","Pudge","Sand King","Slardar","Snapfire","Spirit Breaker","Sven","Tidehunter","Timbersaw","Tiny","Treant Protector","Tusk","Underlord","Undying","Wisp","Wraith King"]
agil = ["Anti-Mage","Arc Warden","Bloodseeker","Bounty Hunter","Broodmother","Clinkz","Drow Ranger","Ember Spirit","Faceless Void","Gyrocopter","Hoodwink","Juggernaut","Lone Druid","Luna","Medusa","Meepo","Mirana","Monkey King","Morphling","Naga Siren","Nyx Assassin","Pangolier","Phantom Assassin","Phantom Lancer","Razor","Riki","Shadow Fiend","Slark","Sniper","Spectre","Templar Assassin","Terrorblade","Troll Warlord","Ursa","Vengeful Spirit","Venomancer","Viper","Weaver"]
inte = ["Ancient Apparition","Bane","Batrider","Chen","Crystal Maiden","Dark Seer","Dark Willow","Dazzle","Death Prophet","Disruptor","Enchantress","Enigma","Grimstroke","Invoker","Jakiro","Keeper of the Light","Leshrac","Lich","Lina","Lion","Nature's Prophet","Necrophos","Ogre Magi","Oracle","Outworld Devourer","Puck","Pugna","Queen of Pain","Rubick","Shadow Demon","Shadow Shaman","Silencer","Skywrath Mage","Storm Spirit","Techies","Tinker","Visage","Void Spirit","Warlock","Windranger","Winter Wyvern","Witch Doctor","Zeus"]
role1 = ["Legion Commander","Sven","Tiny","Chaos Knight","Lifestealer","Lycan","Wraith King","Anti-Mage","Drow Ranger","Gyrocopter","Lone Druid","Juggernaut","Luna","Naga Siren","Morphling","Riki","Phantom Lancer","Templar Assassin","Sniper","Ursa","Troll Warlord","Clinkz","Medusa","Faceless Void","Phantom Assassin","Slark","Terrorblade","Spectre","Weaver",]
role2 = ["Tiny","Magnus","Night Stalker","Ember Spirit","Lone Druid","Morphling","Riki","Templar Assassin","Sniper","Bloodseeker","Broodmother","Medusa","Meepo","Razor","Shadow Fiend","Viper","Lina","Puck","Rubick","Silencer","Storm Spirit","Windranger","Tinker","Zeus","Batrider","Death Prophet","Leshrac","Invoker","Outworld Devourer","Necrophos","Queen of Pain","Pugna","Visage"]
role3 = ["Legion Commander","Omniknight","Phoenix","Timbersaw","Tiny","Axe","Chaos Knight","Doom","Lycan","Magnus","Night Stalker","Pudge","Sand King","Slardar","Spirit Breaker","Undying","Tidehunter","Bounty Hunter","Lone Druid","Mirana","Riki","Ursa","Vengeful Spirit","Clinkz","Broodmother","Faceless Void","Nyx Assassin","Razor","Viper","Venomancer","Weaver","Enchantress","Nature's Prophet","Puck""Silencer","Batrider","Dark Seer","Enigma","Outworld Devourer","Necrophos","Pugna"]
role4 = ["Omniknight","Phoenix","Tiny","Treant Protector","Tusk","Abaddon","Night Stalker","Pudge","Sand King","Spirit Breaker","Undying","Bounty Hunter","Mirana","Vengeful Spirit","Nyx Assassin","Venomancer","Jakiro","Enchantress","Lina","Keeper of the Light","Nature's Prophet","Shadow Shaman","Rubick","Skywrath Mage","Silencer","Windranger","Enigma","Invoker","Pugna","Winter Wyvern"]
role5 = ["Abaddon","Undying","Chen","Disruptor","Crystal Maiden","Jakiro","Keeper of the Light","Ogre Magi","Oracle","Shadow Shaman","Rubick","Skywrath Mage","Silencer","Ancient Apparition","Bane","Dazzle","Lion","Lich","Shadow Demon","Winter Wyvern","Warlock","Witch Doctor"]
cores = ["Legion Commander","Sven","Tiny","Chaos Knight","Lifestealer","Lycan","Wraith King","Anti-Mage","Drow Ranger","Gyrocopter","Lone Druid","Juggernaut","Luna","Naga Siren","Morphling","Riki","Phantom Lancer","Templar Assassin","Sniper","Ursa","Troll Warlord","Clinkz","Medusa","Faceless Void","Phantom Assassin","Slark","Terrorblade","Spectre","Weaver","Magnus","Night Stalker","Ember Spirit","Bloodseeker","Broodmother","Meepo","Razor","Shadow Fiend","Viper","Lina","Puck","Rubick","Storm Spirit","Windranger","Tinker","Zeus","Batrider","Death Prophet","Leshrac","Invoker","Outworld Devourer","Necrophos","Queen of Pain","Pugna","Visage","Omniknight","Phoenix","Timbersaw","Axe","Doom","Pudge","Sand King","Slardar","Spirit Breaker","Undying","Tidehunter","Bounty Hunter","Mirana","Vengeful Spirit","Nyx Assassin","Viper","Venomancer","Weaver","Enchantress","Nature's Prophet","Silencer","Dark Seer","Enigma"]
supps = ["Omniknight","Phoenix","Tiny","Treant Protector","Tusk","Abaddon","Night Stalker","Pudge","Sand King","Spirit Breaker","Undying","Bounty Hunter","Mirana","Sniper","Vengeful Spirit","Nyx Assassin","Venomancer","Weaver","Chen","Disruptor","Crystal Maiden","Jakiro","Enchantress","Lina","Keeper of the Light","Ogre Magi","Nature's Prophet","Oracle","Shadow Shaman","Rubick","Silencer","Windranger","Ancient Apparition","Bane","Dazzle","Enigma","Invoker","Lion","Lich","Pugna","Visage","Shadow Demon","Winter Wyvern","Warlock","Witch Doctor"]
jungle = ["Nature's Prophet","Legion Commander","Batrider","Axe","Lifestealer","Chaos Knight","Lycan","Enchantress","Chen","Mirana","Crystal Maiden","Sand King","Sniper","Play with your team you nerd"]